### ISSUE TITLE
FR: Add option to 'remember' headers

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-playground#104]
So when you open a new query tab, the same headers would be sent. Cannot think of any use case where this isn't desired, so maybe even make this the default behavior.

**Comment by tlvenn** [comment]
I wonder if global headers (shared across tabs) wouldn't be more useful. If you have 12 tabs already and you need to change your auth header, it gonna be painful. And if an header is redefined locally for the tab, it would override the global one.

**Comment by timsuchanek** [comment]
The "remember headers" option is now part of the settings. I open a separate issue for global headers.
