### ISSUE TITLE
Q: Clarify the interaction between graphql-config, graphql-cli and graphcool-cli

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-playground#106]
All specify environments, in one way or another. The docs mention compatibility with graphql-config, but I would also have expected graphcool-cli in there.

**Comment by timsuchanek** [comment]
The graphcool cli, prisma cli & graphql cli all now resolve the graphql config already and pass it into the express middleware.

In the case of the electron app: It uses `graphql-config-extension-graphcool` and `graphql-config-extension-prisma` under the hood to resolve graphql configs that points to graphcool or prisma projects.

As we don't want to ship this overhead in the `graphql-playground-html` package and it introduces a security risk, these packages are only included in the electron app.
