### ISSUE TITLE
Visible scrollbars and strange gradient on the right side of window

### ISSUE THREAD

**Issue by OlegIlyenko** [graphcool/graphql-playground#107]
It looks a bit strage. Maybe some css issue?

<img width="1181" alt="graphql_playground_and_applications" src="https://user-images.githubusercontent.com/156569/30881514-69d01fe6-a306-11e7-85d7-89a834df50f5.png">

**Comment by kbrandwijk** [comment]
Same on Windows.

**Comment by timsuchanek** [comment]
Fixed in latest release
