### ISSUE TITLE
FR: Install a protocol handler with Electron app, to be able to open a local playground from the web

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-playground#123]
- Add a button to the online playground to open locally
- Create a protocol handler (for example: graphql://......) and register that with the electron app. This is supported on Windows, Linux and MacOS.

**Comment by timsuchanek** [comment]
This is now implemented and being used by both the prisma and graphql cli.
The url looks like this:
`graphql-playground://?cwd=${process.cwd()}&envPath=${envPath}&endpoint=${myEndpoint}`

`cwd` is the current working directory for the case that a graphqlconfig file should be loaded.
`envPath` is the path to a file containing the env vars to be loaded.
`endpoint` is the url of the endpoint.

Either `cwd` & `envPath` can be provided, or `endpoint` works on it's own.
