### ISSUE TITLE
Blog post links directly to mac dmg only (twice) instead of GH releases

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-playground#124]
https://medium.com/@graphcool/f1e0a018f05d

**Comment by nikolasburk** [comment]
We're linking two times to the GitHub repo, in the first and in the last paragraph. And two times to the direct download, once in the caption of the header image and another time two paragraphs after that image.

Which links would you expect to be different?

**Comment by kbrandwijk** [comment]
I meant the two direct download links. The Github repo readme points to the releases on Github, which is also still empty, but I think it makes sense they link to a place where you can find the executables for all platforms, right?

**Comment by nikolasburk** [comment]
I see, thanks for the hint! I think you're right and we should link to the GitHub releases. I updated the links in the blog post accordingly.
