### ISSUE TITLE
[1.0.1] Can't delete headers

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-playground#131]
'x' doesn't work

(Hosted version)

**Comment by kbrandwijk** [comment]
Also, the local version (Windows) is a little bit less bad. Clicking the 'x' doesn't appear to work, but when you close the headers popup, it is removed.

**Comment by marktani** [comment]
Clicking the close button results in this error for me:

![image](https://user-images.githubusercontent.com/1780597/31727798-d3c6ceb0-b42a-11e7-9ec4-83d236c7a2d7.png)

**Comment by timsuchanek** [comment]
Fixed in latest version
