### ISSUE TITLE
[1.0.1] What's the logic behind the 'reshare' button?

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-playground#134]
If I make a change, the button changes to 'reshare', but if I press that, it will also change back to 'share'. What's the logic behind 'reshare' vs 'share' (the wording), because both create a _new_ share URL.

**Comment by timsuchanek** [comment]
The idea is just that if you already shared, you should see reshare instead of share. To make people aware, that this already has been shared.
