### ISSUE TITLE
[1.0.1] Subscriptions don't work

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-playground#136]
Which makes sense, because you don't know the subscription endpoint. However, subscription is in the intellisense, and a red dot is shown next to the tab header when play is clicked, and clicking play again gives:
`Cannot read property 'subscribe' of undefined`

Also, the subscription endpoint is not accepted:
![image](https://user-images.githubusercontent.com/852069/30919789-b651b1b2-a3a2-11e7-8239-53a6f17d374c.png)

I put 'testing your subscriptions' in my Producthunt review, so it would be nice if it actually worked :see_no_evil:

**Comment by kbrandwijk** [comment]
Ùpdate: not entirely; it turns out that subscriptions without a filter don't work. Adding a filter causes the subscription to run, but then logging is not right:
![image](https://user-images.githubusercontent.com/852069/30920293-e2aef2a0-a3a3-11e7-8fd7-2cfcf0df15aa.png)

**Comment by kbrandwijk** [comment]
Also, copy-pasting a subscription to a new tab, will cause the same error as in the original description above...
![image](https://user-images.githubusercontent.com/852069/30920354-047e231a-a3a4-11e7-9ec9-9ebc014a43e0.png)

**Comment by kbrandwijk** [comment]
Related question, for a non-Graphcool endpoint, how would you know the subscriptions endpoint?

**Comment by timsuchanek** [comment]
Can you try again? Just fixed this in 1.0.4.
Regarding auth: We are taking the same auth headers and inject them to the `connctionParams` of [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws)
We may, however put this information into the docs.
PRs welcome!
And reopen of course if still and issue!

**Comment by artisologic** [comment]
I'm with @kbrandwijk, it seems subscriptions endpoints are somewhat hardcoded to graphcool.
I can't seem to be able to play subscriptions from a non-graphcool endpoint.
What's the process I should go through?
