### ISSUE TITLE
Electron: Support localhost URLs

### ISSUE THREAD

**Issue by overra** [graphcool/graphql-playground#138]
As of `1.0.1`, `http://localhost:3000/graphql` is not a valid URL Endpoint. This is because `isURL` looks for a TLD by default. I believe adding the `{ require_tld: false }` option to the `isURL` below would fix this.

https://github.com/graphcool/graphql-playground/blob/9d459d998788985c22491c3c7013f078c548c0dd/packages/graphql-playground-electron/src/InitialView/InitialView.tsx#L72

**Comment by overra** [comment]
Yes, I'll try to get to it today, after work 😄

**Comment by batjko** [comment]
Yea, this should really not happen:

![selection_234](https://user-images.githubusercontent.com/7287076/30978197-bebbd042-a471-11e7-92dd-c5f2a479bd6d.png)

**Comment by andrewtpoe** [comment]
Temporary workaround for now...

Select one of the sample api's.
Click settings button in top right.
Update route to use `http://localhost:3000/graphql`.
Should now work correctly.

That said, I look forward to when this is resolved. Great work on this tool!

**Comment by entropitor** [comment]
@andrewtpoe Your workaround doesn't seem to work for me. It keeps the old schema
