### ISSUE TITLE
Development Issues

### ISSUE THREAD

**Issue by DevanB** [graphcool/graphql-playground#141]
Thanks for such an awesome project. I recently wanted to try something with the code (and perhaps submit a PR for it), but I ran into a few issues. I don't use TypeScript regularly, and these could be small issues. I'll try to be as thorough as possible!

TypeScript version: 2.3.4 (the best I can tell).

When I clone, `cd packages/graphql-playground`, and run `yarn && yarn start` I am presented with an error:

```
.../packages/graphql-playground/lib/components/Playground.d.ts
(6,27): error TS6143: Module '../reducers/graphiql-docs' was resolved to '/Users/devanbeitel/Projects/graphql-playground/packages/graphql-playground/lib/reducers/graphiql-docs.js', but '--allowJs' is not set.
```

No problem, I'll just add `allowJs: true` to `tsconfig.json`. Luckily that fixes that issue, but then I hit another issue:

```
.../packages/graphql-playground/lib/components/Playground.d.ts
(6,10): error TS2305: Module '"/Users/devanbeitel/Projects/graphql-playground/packages/graphql-playground/lib/reducers/graphiql-docs"' has no exported member 'DocsState'.
```

This issue perplexed me enough to look into the built source and a few other places. None of which seemed to show any obvious signs of how to fix the problem.

Am I missing something obvious (I totally could be!)? I understand this could get lengthy, but am willing to work through it all :)

**Comment by timsuchanek** [comment]
Thanks @DevanB for filing this issue! It was a problem in the tsconfig, which should be fixed now. Closing this for now, feel free to reopen when it's still an issue!
