### ISSUE TITLE
Middleware options don't work

### ISSUE THREAD

**Issue by jansenignacio** [graphcool/graphql-playground#150]
I'm using apollo-graphql and I tried to use graphql-playground as a graphiql replacement. I found that the middleware options don't work.

I tried something like the following:

```
app.use('/api/graphiql', playground({
  endpointUrl: '/api/graphql',
  subscriptionsUrl: '/api/graphql/subscriptions'
});
```

but when I load playground on my browser, the endpointUrl and subscriptionsUrl on the settings popup are as follows:

```
GraphQL Endpoint: {APP_URL}/api/graphiql
Subscriptions Endpoint: {APP_URL}/api/graphql
```

**Comment by albinekb** [comment]
I have a similar issue, when I followed the example for express
`app.use('/playground', playgroundMiddleware({ endpointUrl: '/graphql' }))`

But if i go to /playground the route is `${APP_URL}/playground`, not `/graphql` as expected..

**Comment by albinekb** [comment]
fan-tastic ❤️  @timsuchanek
