### ISSUE TITLE
Can't set headers after they are sent

### ISSUE THREAD

**Issue by nuttikung** [graphcool/graphql-playground#160]
I use graphql with express, it's working with graphiql.

For playground I got error message from Client and server site as attached files.

<img width="1280" alt="screen shot 2017-10-01 at 12 11 38 am" src="https://user-images.githubusercontent.com/8456620/31047924-8b660c30-a63d-11e7-8dba-ab13fd1ef64e.png">
<img width="1280" alt="screen shot 2017-10-01 at 12 11 57 am" src="https://user-images.githubusercontent.com/8456620/31047925-8baf3a18-a63d-11e7-81d5-991a52e03d0d.png">
<img width="564" alt="screen shot 2017-10-01 at 12 12 09 am" src="https://user-images.githubusercontent.com/8456620/31047926-8bb81aac-a63d-11e7-8f59-9192336be204.png">

Module Dependencies : 
graphql - 0.11.2
express-graphql - 0.6.11
graphql-playground - 1.0.4
express - 4.14.0

If any information, please let me know.

**Comment by cgx9** [comment]
+1

**Comment by timsuchanek** [comment]
This should be fixed in the latest playground version. Please reopen if still an issue

**Comment by Jamakase** [comment]
Still have this issue. Last version in npm is 1.3.17. Is it possible to install 1.4.2 somehow?

**Comment by adamjking3** [comment]
Still an issue here as well.
