### ISSUE TITLE
Blocking: Share button no longer working

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-playground#173]
Nothing happens when I press it.

**Comment by sorenbs** [comment]
For me sharing does work, unless I disable sharing http headers:

![image](https://user-images.githubusercontent.com/281337/31814451-f347b046-b589-11e7-9d96-8d95504bd146.png)

Then I get this error:

```
Uncaught TypeError: Cannot assign to read only property 'headers' of object '#<Object>'
    at Playground.tsx:1480
    at lodash.js:13379
    at lodash.js:4944
```

Could that be the issue you are seeing?

**Comment by timsuchanek** [comment]
This should be fixed by now. Reopen if still an issue
