### ISSUE TITLE
Autocomplete does not include types of input fields

### ISSUE THREAD

**Issue by marktani** [graphcool/graphql-playground#175]
This makes it difficult to determine which fields are required, and what their type is.

For example, in this situation, `String!` should be shown:

![image](https://user-images.githubusercontent.com/1780597/31438817-08066286-ae8a-11e7-9d6a-74ecf139d347.png)

**Comment by morajabi** [comment]
You mean in front of every dropdown item?

**Comment by marktani** [comment]
No, this is what should be shown:

```
name (selected)
moviesIds
movies
---
String! <leave 'Self descriptive.' out>
```

`String!`, because `name` is a required String.

**Comment by morajabi** [comment]
Aha! Can I implement it?

**Comment by timsuchanek** [comment]
@morajabi go for it! It could be a css issue, you may start checking if it is in the dom. In the `QueryEditor.tsx` you can turn off the automatic closing of the codemirror for debugging.

**Comment by morajabi** [comment]
Hey @timsuchanek! I see something like this in the GraphCMS's API explorer. Is that what we want?
![screen shot 2017-10-17 at 11 18 16 am](https://user-images.githubusercontent.com/12202757/31652718-e7a3973c-b32c-11e7-92b8-e53ce4bc4b72.png)

**Comment by marktani** [comment]
You don't need to add this manually, this type information is already available in the schema. For some reasons, the type is not shown for input fields currently, though.
