### ISSUE TITLE
Layout issues with Firefox

### ISSUE THREAD

**Issue by yliaho** [graphcool/graphql-playground#177]
![gif demo](https://i.imgur.com/8ysVw0I.gif)

Firefox Developer Edition (57.0b7 (64-bit)) on macOS has several deal-breaker issues with the layout. I haven't tested other with other browser except Chrome (which is fine).  
  
* The bottom part of the window with buttons seems to sink down beyond reach when executing stuff.  
* The result window is not scrollable. Results that exceed the viewport height aren't reachable.  
* The body seems to have `overflow: scroll`? (see the empty scroll track on the right)  
* Top bar has vertical scroll for no reason.  
  
Let me know if you need further info. Would love to get this fixed. :)

**Comment by timsuchanek** [comment]
Just tested in latest firefox dev edition and it looks like expected.
Please reopen if still an issue.

**Comment by m4con** [comment]
Looks as it appears again. Firefox 74.0 (64-Bit) and Version 80.0.3987.149 (Offizieller Build) (64-Bit) on Windows 10. 

- No horizontal scrollbar if there are many tabs open (Chrome only on hover and hard to see)
- No scrollbar for the whole output section in subscription context (only for individual outputs)

![Capture](https://user-images.githubusercontent.com/4339750/77842963-b42c6f00-7198-11ea-9179-2db881b2d145.PNG)
