### ISSUE TITLE
Variable autocomplete is at wrong position

### ISSUE THREAD

**Issue by marktani** [graphcool/graphql-playground#181]
![pasted image at 2017_10_16 07_18 pm](https://user-images.githubusercontent.com/1780597/31636460-cfa821d2-b2ca-11e7-8f4e-371050e37afc.png)

**Comment by Huvik** [comment]
Still actual? Because there is no autocompletion for variables right now.

**Comment by timsuchanek** [comment]
Should work like expected by now. Please reopen if still an issue 
![image](https://user-images.githubusercontent.com/1094804/35107045-37957abc-fc70-11e7-9689-522625c469e5.png)
