### ISSUE TITLE
Inline the SVG icons in React components to support SSR with NextJS

### ISSUE THREAD

**Issue by morajabi** [graphcool/graphql-playground#190]
We can inline the SVG icon files in `/assets` folder into exportable React components, like this for example: 

```js
// icons.js
export const SendIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="17" height="15" xmlnsXlink="http://www.w3.org/1999/xlink">
    <title>send</title>
    <path fill="#2EA4FF" d="M0 15l17-7.5L0 0v5.8l12 1.7L0 9.2V15z"/>
  </svg>
)
```

This will also fix #165

**Comment by hepin1989** [comment]
Yes, I could not import it ,with https://github.com/kesne/babel-plugin-inline-react-svg did not help.

**Comment by morajabi** [comment]
@hepin1989 Isn't it solved now? @timsuchanek worked on a quick fix to inline SVGs with Webpack.

**Comment by timsuchanek** [comment]
This should be fixed by now. Reopen when still an issue
