### ISSUE TITLE
No scrolling in long json resposes

### ISSUE THREAD

**Issue by arquio** [graphcool/graphql-playground#202]
The frame no scroll when the respose is very long. 

![playground](https://user-images.githubusercontent.com/414590/32169047-2595688a-bd6f-11e7-9656-cd5bad4d8a30.gif)

#200 ### This issue pertains to:

- [x] GraphQL Playground - Electron App
- [x] GraphQL Playground

**Comment by timsuchanek** [comment]
This is fixed in the latest version
