### ISSUE TITLE
Package installation with yarn fails because of the deasync package

### ISSUE THREAD

**Issue by slashmo** [graphcool/graphql-playground#203]
#### This issue pertains to:

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground

#### What OS and OS version are you experiencing the issue(s) on?
macOS High Sierra

#### What version of graphql-playground(-electron) are you experience the issue(s) on?
1.1.0

#### What is the expected behavior?
After a fresh clone of the project one should be able to "cd" into `packages/graphql-playground` and run `yarn install` to install the node modules.

#### What is the actual behavior?
Currently `yarn install` errors out because of the following error:

```
error /path/to/repo/graphql-playground/packages/graphql-playground/node_modules/deasync: Command failed.
Exit code: 1
Command: node ./build.js
Arguments:
Directory: /path/to/repo/graphql-playground/packages/graphql-playground/node_modules/deasync
Output:
events.js:183
      throw er; // Unhandled 'error' event
```

Node version: v8.9.0
Yarn version: 1.2.1

#### What steps may we take to reproduce the behavior?
- `git clone git@github.com:graphcool/graphql-playground.git`
- `cd packages/graphql-playground`
- `yarn`

**Comment by timsuchanek** [comment]
Can't reproduce right now, as we also have a CI setup that builds successfully.
Please reopen if still an issue.
