### ISSUE TITLE
Schema docs broken in 1.1

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#204]
Since the newest release, the schema docs are completely broken. Keyboard shortcuts don't seem to work either.

![kapture 2017-11-02 at 11 21 17](https://user-images.githubusercontent.com/1567498/32343252-155556a8-bfc0-11e7-8d27-7e69973fc177.gif)

**Comment by timsuchanek** [comment]
Fixed by https://github.com/graphcool/graphql-playground/commit/9a86ac3b73f042b597c32c7b9399ba372cfb7c1b
