### ISSUE TITLE
TypeScript errors

### ISSUE THREAD

**Issue by kaihaase-wd** [graphcool/graphql-playground#205]
#### This issue pertains to:

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground

#### What OS and OS version are you experiencing the issue(s) on?
macOS High Sierra (10.13)

#### What version of graphql-playground(-electron) are you experience the issue(s) on?
"graphql-playground-middleware": "1.1.0"

#### What is the expected behavior?
No errors during the compiling via tsc

#### What is the actual behavior?
```
$ tsc
node_modules/graphql-playground-middleware/dist/hapi.d.ts(1,24): error TS2307: Cannot find module 'hapi'.
node_modules/graphql-playground-middleware/dist/koa.d.ts(1,25): error TS2307: Cannot find module 'koa'.
node_modules/graphql-playground-middleware/dist/koa.d.ts(3,33): error TS7006: Parameter 'options' implicitly has an 'any' type.
```

#### What steps may we take to reproduce the behavior?
Add package
```
$ yarn add graphql-playground-middleware
```

Integrate playground
```
import * as express from 'express';
import { expressPlayground as graphqlPlayground } from 'graphql-playground-middleware';

// Create express application
this._app = express();

// Add playground
this.app.use('/playground', graphqlPlayground({
    endpoint: '/api'
}));
```

Compile typescript file
```
$ tsc
```

**Comment by timsuchanek** [comment]
We moved the express middleware to `graphql-playground-middleware-express`.
This should be fixed in there.
Please reopen if still an issue.
