### ISSUE TITLE
Create different middleware packages for different servers

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-playground#210]
Currently, there's only one middleware package, `graphql-playground-middleware`, surprisingly introduced in the latest release. This is a good step forward, but to minimize unnecessary dependencies, and to align better with the `apollo-server-...` packages, it would be better to have separate packages for each server type:

`graphql-playground-hapi`, `graphql-playground-express`, `graphql-playground-koa` etc.

**Comment by morajabi** [comment]
So, I'll do this if others are OK.

**Comment by kbrandwijk** [comment]
I think this can be closed as implemented?

**Comment by timsuchanek** [comment]
Yes.
