### ISSUE TITLE
Different results in playground vs standalone REST client

### ISSUE THREAD

**Issue by Falconerd** [graphcool/graphql-playground#217]
I got the correct using [Insomnia](https://insomnia.rest), but not using the playground client. Tried using existing database and following the steps outlined below.

#### This issue pertains to:

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground

#### What is the expected behavior?

```
{
  "data": {
    "loggedInUser": {
      "id": "cizjh26dujm7f0190j1jovkhb"
    }
  }
}
```

#### What is the actual behavior?

```
{
  "data": {
    "loggedInUser": null
  }
}
```

#### What steps may we take to reproduce the behavior?

1. `yarn add global graphcool`
2. `mkdir graphcool-test && cd $_`
2. `graphcool init`
3. `graphcool add-template graphcool/templates/auth/email-password`
4. Uncomment the appropriates lines in the files edited by 3
5. `graphcool deploy`
6. Navigate to your Simple API url in the browser
7. Use the signupUser mutation which returns a token
8. Use the token as a Header with the name Authorization
9. Use the loggedInUser query

**Comment by kbrandwijk** [comment]
Did you use `Bearer` in front of the token? Also, can you check the network tab and grab the actual request being executed?

**Comment by Falconerd** [comment]
That was the issue, cheers... Not sure how I missed that.

![image](https://user-images.githubusercontent.com/1349538/32525185-45ab8640-c477-11e7-91b6-5348f240a459.png)
