### ISSUE TITLE
Support options being passed as function to be called with context

### ISSUE THREAD

**Issue by ksmithut** [graphcool/graphql-playground#220]
#### This issue pertains to:

- [ ] GraphQL Playground - Electron App
- [X] GraphQL Playground

#### What OS and OS version are you experiencing the issue(s) on?

N/A

#### What version of graphql-playground(-electron) are you experience the issue(s) on?

graphql-playground-middleware-express@1.1.2

#### What is the expected behavior?

Be able to pass a function as the options parameter and be able to return the options based on values in the request. The real issue is the 'subscriptionEndpoint' has to be a fully qualified host with path, and I would like to just pass the path, i.e. `'/subscriptions'`, but because it expects the full host and I'm hosting this on a server that accepts requests from multiple hosts (subdomains), I need to dynamically give the subscriptions endpoint the host. I believe this could happen on the client, taking the `window.location` object and getting the host information and prepending the path. I have the same issue with graphiql-express, but they allow you to pass in the options via a function that returns the options, like [this](https://www.apollographql.com/docs/apollo-server/setup.html#options-function)

#### What is the actual behavior?

It only accepts a flat function.

#### What steps may we take to reproduce the behavior?

```js
const url = require('url')
const express = require('express')
const expressPlayground = require('graphql-playground-middleware-express')
const app = express()

app.use('/playground1', expressPlayground({
  endpoint: '/graphql',
  subscriptionEndpoint: '/subscriptions' // I hoped this would work
})

app.use('/playground2', expressPlayground((req) => ({
  endpoint: '/graphql',
  subscriptionEndpoint: url.format({ // I'm okay with this, but would prefer option above
    host: req.get('host'),
    protocol: req.protocol === 'https' ? 'wss' : 'ws',
    slashes: true,
    pathname: '/subscriptions'
  })
}))

// How I'm currently getting around it
app.use('/playground3', (req, res, next) => {
  expressPlayground({
    endpoint: '/graphql',
    subscriptionEndpoint: url.format({
      host: req.get('host'),
      protocol: req.protocol === 'https' ? 'wss' : 'ws',
      slashes: true,
      pathname: '/subscriptions'
    })
  })(req, res, next)
})
```

I'd be happy to submit a PR for it, I'm just unsure which direction you'd want to take it.

**Comment by timsuchanek** [comment]
That's actually a great idea.
You can totally submit a PR for this!
If you want to implement this, the core logic should be implemented in `graphql-playground-html`.
In order to use the `graphql-playground-html` package in the separate middlewares, you have to `yarn link` it.
Today or tomorrow I'm setting up yarn workspaces for this repo, you may want to wait until then in order to save the headache of yarn linking everything.

**Comment by ksmithut** [comment]
Awesome, I'll wait until then :)

**Comment by timsuchanek** [comment]
@ksmithut the workspaces are ready!
You can each out to me in the Graphcool slack if you have any questions, I'm `@tim2` there.

**Comment by ksmithut** [comment]
Oops, meant to cancel a comment

**Comment by ksmithut** [comment]
Looks like graphql-playgrounds supports a relative subscriptions path that just uses window.location. Closing
