### ISSUE TITLE
Can't open a local project with the last framework

### ISSUE THREAD

**Issue by fabien0102** [graphcool/graphql-playground#224]
#### This issue pertains to:

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground

#### What OS and OS version are you experiencing the issue(s) on?
Windows 10

#### What version of graphql-playground(-electron) are you experience the issue(s) on?
v1.1.1

#### What is the expected behavior?
- Open a local project (running on last graphcool framework)
- Have access to permission tab (cf https://www.graph.cool/docs/reference/auth/authorization/permission-queries-iox3aqu0ee#opening-a-new-permission-query-tab)

#### What is the actual behavior?
![image](https://user-images.githubusercontent.com/1761469/32691045-0bcd3efe-c702-11e7-9002-1b215852c557.png)

#### What steps may we take to reproduce the behavior?
1. `graphcool init`
1. Open graphcool playground (electron)
1. Click to `Local`, select the project folder

**Comment by timsuchanek** [comment]
This is fixed in the latest version. Please reopen if still an issue.

**Comment by fabien0102** [comment]
Not really fixed (no .graphqlconfig by default in the base template) 😉 
https://github.com/graphcool/graphcool-framework/issues/6
