### ISSUE TITLE
Hijacks cmd+[/]

### ISSUE THREAD

**Issue by msaspence** [graphcool/graphql-playground#227]
#### This issue pertains to:

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground

#### What OS and OS version are you experiencing the issue(s) on?

macOS 10.13

#### What version of graphql-playground(-electron) are you experience the issue(s) on?

1.1.1

#### What is the expected behavior?

`cmd+[/]` should works across the OS

#### What is the actual behavior?

Intermittently `cmd+[/]` in other applications does nothing. I enabled to pin down how to induce the problem, but quitting playground reliable solves it.

#### What steps may we take to reproduce the behavior?

Unsure

**Comment by timsuchanek** [comment]
Fixed in the latest Electron App :)
