### ISSUE TITLE
Customization for playground

### ISSUE THREAD

**Issue by imranansarij2ee** [graphcool/graphql-playground#229]
Please help with.

Disable changing the endpoint address
Disable sharing (for private APIs you don't want your users to share to graphqlbin)
Override sharing (for internal self-hosted graphqlbin)
Make Playground read-only (so no new tabs or query changes, for demo playgrounds)

**Comment by kbrandwijk** [comment]
Why are you copy-pasting #214?

**Comment by schickling** [comment]
Close in favour of #214. But great points :)
