### ISSUE TITLE
semver versioning

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-playground#230]
Sorry for the CAPS in the title, but _PLEASE_ respect semver versioning. You completely removed the playground from `graphql-playground-middleware` in favor of separate packages per server type from `1.1.2` to `1.1.3`. All package managers will update from 1.1.2 to 1.1.3 silently because it is not expected to have breaking changes.

`1.1.3` should have been `1.2.0` at least, but actually `2.0.0` according to semver, so _ALL_ existing examples don't break when someone installs them!!!

**Comment by timsuchanek** [comment]
Sorry for breaking your build! We should definitely have chosen at least a minor version bump, not just patch. We didn't release a new `graphql-playground-middleware`, so npm and yarn can't install a later version and should stay with `1.1.2`. So what is exactly breaking? Thanks!

**Comment by DevanB** [comment]
@kbrandwijk 

While I don't disagree with correct semantic versioning, there are some steps you should be taking as a developer so package maintainers (we are all human 😄) don't break your builds/examples/software. All of these create a barrier between package creators and yourself, and require you to explicitly declare an upgrade to a package in your software.

If you are using `npm` commands:

1. Change your semver `^` to a `~`: `npm config set save-prefix='~'`.
2. Use `--save-exact` to save an exact package version.
3. `npm shrinkwrap` 🙌.

Also, use Yarn! You lose no functionality, and by default `yarn.lock` operates like `npm shrinkwrap`.

**Comment by kbrandwijk** [comment]
@DevanB Although I appreciate the 'workaround', I don't agree with you. I use `^` because I don't want the overhead of explicitly specifying every version. Patch updates and even minor updates should be backwards compatible. Period. That's how semver versioning works.

Patch = fixes
Minor = fixes and/or new features
Major = breaking changes

**Comment by timsuchanek** [comment]
We're now respecting semver, please reopen if this is still an issue.
