### ISSUE TITLE
Setup CI process that also builds the electron app

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#232]
#### This issue pertains to:

- [x] GraphQL Playground - Electron App
- [x] GraphQL Playground

**Comment by timsuchanek** [comment]
React Playground app is being built, however, there is a dependency of the electron app which behaves weird in circle.
This is a seperate task, the normal Playground build works now.
https://circleci.com/gh/graphcool/graphql-playground/10

**Comment by timsuchanek** [comment]
Done!
