### ISSUE TITLE
Redesign settings popup/workflow

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#234]
This is quite an important "feature" decision which will be the foundation for many future features such as [customization settings](https://github.com/graphcool/graphql-playground/issues/214) and [color themes](https://github.com/graphcool/graphql-playground/issues/74).

This issue is meant to collect requirements, use cases and inspiration for this feature.

## Goal: Easy configuration format & workflow

User configuration should be easy to read, save and share. Default configuration values should be clear and easy to access.

I'm a big fan of [VSCode's settings concept](https://code.visualstudio.com/docs/getstarted/settings) and suggest to adopt the same workflow/implementation.

## Open questions

- [ ] How are settings persisted in web-version?
- [ ] Determine config categories (e.g. workspace, endpoint, global)
- [ ] Configuration shareable via GraphQL Bin?
- [ ] Plugins need to be considered #235

**Comment by kbrandwijk** [comment]
I hate the VSCode way, I find it counter intuitive. I love the Cloud9 settings implementation, where each plugin can add tabs and settings to the settings panel: https://cloud9-sdk.readme.io/docs/settings-and-preferences. It also contains a panel for keybindings by the way...

**Comment by timsuchanek** [comment]
We now implemented a settings tab.
