### ISSUE TITLE
Multi endpoint workflows

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#238]
When working on [GraphQL Native](https://blog.graph.cool/graphql-api-gateway-graphql-native-1e46e4f179f7) applications it's a common scenario to work with multiple GraphQL endpoints at the same time. This workflow should be easily supported by the Playground.

Ideas:

1. Choose endpoint inside of every tab
2. Project panel on the left (see screenshot)

![image](https://user-images.githubusercontent.com/1567498/32943066-42e1c90e-cb8b-11e7-9882-6e1cd5e081a8.png)

**Comment by timsuchanek** [comment]
This is fixed in the latest version. Please reopen if still an issue.
