### ISSUE TITLE
Page goes blank when trying to change endpoint

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-playground#261]
#### This issue pertains to:

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground
- [x] GraphQL Playground **Express Middleware**

#### What version of graphql-playground(-electron) are you experience the issue(s) on?
"graphql-playground-middleware-express": "1.1.4",

#### What is the expected behavior?
I should be able to change the endpoint

#### What is the actual behavior?
As soon as I start typing in the endpoint field, the page goes blank.

#### What steps may we take to reproduce the behavior?
Use the above version in a local gateway project. Open the playground (http://localhost:3000/playground), click on the cog, and type in the endpoint field.

**Comment by timsuchanek** [comment]
This is fixed in the latest version. Please reopen if still an issue.
