### ISSUE TITLE
Tracing isn't supported, but works

### ISSUE THREAD

**Issue by DevanB** [graphcool/graphql-playground#270]
#### This issue pertains to:
- [x] GraphQL Playground - Electron App
- [x] GraphQL Playground

#### What OS and OS version are you experiencing the issue(s) on?
macOS 10.12.6
Firefox, Chrome, and Safari

#### What version of graphql-playground(-electron) are you experiencing the issue(s) on?
graphql-yoga server (0.1.8) using graphql-playground-middleware-express (1.2.0)

#### What is the expected behavior?
Expecting to see no error message when the Apollo Tracing is enabled, and panel is open.

#### What is the actual behavior?
At random times, the error "This GraphQL server doesn’t support tracing. See the following page for instructions: https://github.com/apollographql/apollo-tracing" will appear. However, after running a query, Apollo Tracing will return results.

![tracingoddity](https://user-images.githubusercontent.com/354652/33225340-02e5294e-d13b-11e7-9a4c-89b7d9c1b081.gif)

#### What steps may we take to reproduce the behavior?
1. Create a graphql-yoga server enabling tracing in the config.
2. Start the server, write a query, open the Response Tracing pane, observe if error appears, and run query.
3. Hopefully you have tracing results despite the error you, hopefully, saw in step #2.

**Comment by kbrandwijk** [comment]
That should actually be a warning, not an error.

**Comment by DevanB** [comment]
I believe it shouldn’t be shown at all, because Tracing is working.

**Comment by kbrandwijk** [comment]
Tracing is not working, you are getting an overall trace over the entire request, because Graphcool doesn't include tracing information in the server response.
This is tracing working on a server that provides tracing information:
![image](https://user-images.githubusercontent.com/852069/33227214-6c67c396-d19e-11e7-9a84-fcbd5857c0a5.png)
That's why I think it should be a warning.

**Comment by timsuchanek** [comment]
You were both right!
1. It is better to have as a warning
2. Was just not shown correctly :)

**Comment by timsuchanek** [comment]
Fixed by d58be527e70c6077ed1358def901c76718d80bd5
