### ISSUE TITLE
Error: Could not fetch schema from endpoint//permissions

### ISSUE THREAD

**Issue by marktani** [graphcool/graphql-playground#273]
#### This issue pertains to:

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground

#### What version of graphql-playground(-electron) are you experience the issue(s) on?

1.2

#### What is the expected behavior?

Opening a new workspace with endpoint `https://hello-world-myitqprcqm.now.sh/` works without an error.

#### What is the actual behavior?

![image](https://user-images.githubusercontent.com/1780597/33232178-b91c60ee-d201-11e7-89fc-2c5635167539.png)

#### What steps may we take to reproduce the behavior?

Open `https://hello-world-myitqprcqm.now.sh/` in a new workspace.

**Comment by timsuchanek** [comment]
This is fixed in the latest version. Please reopen if still an issue.
