### ISSUE TITLE
Tracing should not warn that server doesn't support tracing, when in fact it does

### ISSUE THREAD

**Issue by sorenbs** [graphcool/graphql-playground#275]
When first opening the tracing view for https://airbnb.now.sh/ I get the following message

![image](https://user-images.githubusercontent.com/281337/33263359-d64f9f6e-d369-11e7-864a-6fc3991d0ff3.png)

**Comment by kbrandwijk** [comment]
https://github.com/graphcool/graphql-playground/issues/270

**Comment by sorenbs** [comment]
Thanks @kbrandwijk! @schickling is your Airbnb example using an outdated playground?

**Comment by schickling** [comment]
The newest version doesn't seem to be released yet @sorenbs. But this issue should be fixed in the next release.
