### ISSUE TITLE
Sliding schema view switches between error and query result

### ISSUE THREAD

**Issue by marktani** [graphcool/graphql-playground#277]
#### This issue pertains to:

- [x] GraphQL Playground - Electron App
- [?] GraphQL Playground
- [ ] GraphQL Playground Middleware

#### What OS and OS version are you experiencing the issue(s) on?

MacOS

#### What version of graphql-playground(-electron/-middleware) are you experience the issue(s) on?

Version 1.2.0 (1.2.0)

#### What is the expected behavior?

Sliding the schema does not switch between error message and query result.

#### What is the actual behavior?

https://youtu.be/VWnUgU6VhZ4

#### What steps may we take to reproduce the behavior?

* Connect to a Graphcool permission schema without the correct authorization header
* Reload the Schema (results in red error message)
* Enter the correct authorization header
* Send a query (results in data response)
* Open schema view (results in red error message)

**Comment by timsuchanek** [comment]
This is fixed in the latest version. Please reopen if still an issue.
