### ISSUE TITLE
1.3 Release feedback

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#282]
Before cutting the 1.3 release, we should fix the following issues:

**Comment by schickling** [comment]
- [ ] HTTP headers are wrong for introspection query

![image](https://user-images.githubusercontent.com/1567498/33441085-1a302ca0-d5f2-11e7-9ddc-e076c56cc417.png)

**Comment by schickling** [comment]
- [ ] Once the schema sidebar was toggled, there is a white overlap

![image](https://user-images.githubusercontent.com/1567498/33441143-3e4ec362-d5f2-11e7-8e34-88c1c99c8b96.png)

**Comment by schickling** [comment]
- [ ] Most right selection element should be blue instead of grey

![image](https://user-images.githubusercontent.com/1567498/33441179-58c2060a-d5f2-11e7-9b6a-55a5ea817419.png)

**Comment by schickling** [comment]
- [ ] HTTP headers should have a count of headers (example: `HTTP HEADERS (2)`

![image](https://user-images.githubusercontent.com/1567498/33441248-8421aa94-d5f2-11e7-9657-038ae6f30321.png)

**Comment by schickling** [comment]
- [ ] HTTP headers overlap

![image 2](https://user-images.githubusercontent.com/1567498/33441293-a32d661c-d5f2-11e7-8353-ebcc7aa7810f.png)

**Comment by schickling** [comment]
- [ ] Main settings should be under `editor` namespace

![image](https://user-images.githubusercontent.com/1567498/33441409-e7209d9e-d5f2-11e7-863e-85c06f9ab719.png)

Example:

```json
{
  "editor.theme": "dark",
  "editor.reuseHeaders": true
}
```

**Comment by schickling** [comment]
- [ ] `graphql playground` is blocking

**Comment by schickling** [comment]
- [ ] `graphql playground` doesn't work if GraphQL Playground wasn't open before

**Comment by schickling** [comment]
- [ ] Double click a `*.graphql` file doesn't open file but just playground

**Comment by timsuchanek** [comment]
- [ ] cli first open window not opening file correctly

**Comment by schickling** [comment]
- [ ] panels jump & cannot be resized properly

![kapture 2017-11-23 at 19 33 26](https://user-images.githubusercontent.com/1567498/33475298-36e0ef9c-d67e-11e7-8127-4f54fbe1d54a.gif)

**Comment by schickling** [comment]
- [ ] Tabs cut off at the wrong spot

![image](https://user-images.githubusercontent.com/1567498/33476391-20bc865a-d682-11e7-8032-6d1f4b3f85a7.png)
