### ISSUE TITLE
Schema sidebar displaced once opened

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#284]
- [ ] Once the schema sidebar was toggled, there is a white overlap

![image](https://user-images.githubusercontent.com/1567498/33441143-3e4ec362-d5f2-11e7-8e34-88c1c99c8b96.png)

**Comment by Huvik** [comment]
Can you reproduce it? I have it ok

**Comment by schickling** [comment]
Yes, try to toggle the schema sidenav and then go back and forth between tabs in the electron app.

**Comment by Huvik** [comment]
Ah i thought its just web version

**Comment by timsuchanek** [comment]
This is fixed in the latest version. Please reopen if still an issue.
