### ISSUE TITLE
Copying curl doesn't work for empty variables

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#285]
When trying to run a copied `curl` statement when there are no query variables provided (or even needed), that means the query variables field is empty, it results in the following error:

![image](https://user-images.githubusercontent.com/1567498/33483853-06ec06ce-d6a0-11e7-8dce-77110b95847d.png)

Current workaround: Enter `{}` in the variables input.

**Comment by timsuchanek** [comment]
This is fixed in the latest version. Please reopen if still an issue.
