### ISSUE TITLE
Hide close icon for inactive tabs

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#289]
Currently, the close icon is visible for all tabs. The close icon should just be visible for the currently selected and/or hovered tab. (See the implementation of VSCode.)

**Comment by kbrandwijk** [comment]
For illustration purposes:
![hideclose](https://user-images.githubusercontent.com/852069/33491947-0171e35a-d6bc-11e7-862a-a5d36e1cc5be.gif)
