### ISSUE TITLE
Security concern: Deploying graphql-config context to production

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#294]
While locally it's very convenient that the playground works out of the box with `.graphqlconfig` including environment variables, this might be a security concern when deploying to non-local environments.

We should discuss this issue further and come up with strategies to deal with this situation.

**Comment by DevanB** [comment]
Was this addressed and deployed @schickling ?

**Comment by schickling** [comment]
Yes, this is now addressed by the `env` option in the latest Playground middleware releases.
