### ISSUE TITLE
Desktop version of Playground removes extensions object when using tracing

### ISSUE THREAD

**Issue by StirlingBaker** [graphcool/graphql-playground#303]
#### This issue pertains to:

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground
- [ ] GraphQL Playground Middleware

#### What OS and OS version are you experiencing the issue(s) on?

Mac OS X Sierra 10.12.6

#### What version of graphql-playground(-electron/-middleware) are you experience the issue(s) on?

GraphQL Playground OS X App v 1.3.0

#### What is the expected behavior?

Connecting to a GraphQL API that has implemented Apollo Tracing.
https://www.npmjs.com/package/apollo-tracing

When running a query, expect to see tracing data in the Tracing panel, and `data` and `extensions` objects in the response panel. 

#### What is the actual behavior?

Connecting to a GraphQL API that has implemented Apollo Tracing.

When running a query, we now get the Playground tracing panel data (awesome), but the GraphQL response itself no longer includes the `extensions` object, just the `data` object. 

#### What steps may we take to reproduce the behavior?

If needed, I can provide a link to our API. 

Screenshots of response for the same query in GraphiQL and GraphQL Playground MacOS v1.3.0

![graphiql-tracing](https://user-images.githubusercontent.com/3048209/33505120-0295dfec-d69f-11e7-920e-381b24ef68cf.png)
![playground-tracing](https://user-images.githubusercontent.com/3048209/33505121-02b6b64a-d69f-11e7-9230-0b024c53964b.png)

**Comment by kbrandwijk** [comment]
Seems to happen here: https://github.com/graphcool/graphql-playground/blob/master/packages/graphql-playground/src/components/Playground/GraphQLEditor.tsx#L904

**Comment by schickling** [comment]
This is not really a bug but something that should be configurable. I suggest the following setting: ```json
{ "tracing.hideExtensionsResponse": true }
```

**Comment by kbrandwijk** [comment]
It's important to note that the current implementation deletes the entire extensions key. Even if this was configurable, it should only remove `tracing` from extensions, not everything that's in there!

**Comment by morajabi** [comment]
I'll tackle this tomorrow morning
