### ISSUE TITLE
History persistence seems to be broken since v1.3.5 

### ISSUE THREAD

**Issue by vincenzo** [graphcool/graphql-playground#312]
#### This issue pertains to:

- [X] GraphQL Playground - Electron App
- [X] GraphQL Playground
- [X] GraphQL Playground Middleware

Don't have much time to write right now, but load up PG (>= v1.3.5 and <=1.3.6) somewhere and see how it doesn't save the history. I've observed this on two projects so far.

## What should happen

1. Go to any PG
2. Run your queries
3. The queries are saved in the history
4. The queries are still there when you reopen the same PG on the same browser

## What actually happens
...
...
4. The queries **are no longer there** when you reopen the same PG on the same browser

## How to replicate

Get a PG (>= v1.3.5 and <=1.3.6) up and running in any project (my favourite is to create a new one with graphql-yoga). I tried also on https://www.graphqlbin.com/Agjcr and it breaks there, too. When I open it, there's a history available there already (not from me), but any new queries do not persist.

**Comment by sorenbs** [comment]
It seems to work here https://www.graphqlbin.com/Agjcr

I'm unsure if this is version 1.3.5 though. @timsuchanek we should add the version number in the UI somewhere :-)

**Comment by vincenzo** [comment]
@sorenbs Thanks. Could you try and build a quick project off graphql-yoga? 

PS: yes, the version number in the UI is a very good idea.

**Comment by morajabi** [comment]
@sorenbs Made an issue and will tackle this later: https://github.com/graphcool/graphql-playground/issues/314 Good suggestion 😉

**Comment by vincenzo** [comment]
Thanks @morajabi. 

Btw @sorenbs @timsuchanek, I'll update the description with a clearer description.

**Comment by vincenzo** [comment]
The only place in the codebase where I can see `saveHistory()` has been commented out is [here](https://github.com/graphcool/graphql-playground/blob/0ebd6d50eb6c146b472da096f3874e775018ff0d/packages/graphql-playground/src/components/Playground.tsx#L244). 

Going by the codebase, I understood that `saveHistory()` is also called when a query is shared, so I tried sharing, and indeed the history is saved permanently. The previous behaviour I had (which was when I had installed middleware-express 1.3.1) was that running the query and then closing the window where PG was running was enough for the history to be saved. Now it's not doing it and I can only put it down to the commented out code I linked above. 

Thoughts?

**Comment by vincenzo** [comment]
This is the commit that introduced that change: https://github.com/graphcool/graphql-playground/commit/a43266e69a360575c0c6ef4b1c938c7376b9fbc6 - It doesn't seem like something that was actually meant? I can't see the relation with the rest of the change in that commit.

**Comment by vincenzo** [comment]
@sorenbs @timsuchanek Any feedback on whether or not my findings are actually relevant to the issue at hand?

**Comment by vincenzo** [comment]
@kbrandwijk Maybe you have an opinion about this one? I am trying to restore this functionality.

**Comment by vincenzo** [comment]
Anyone looking at this or #317?

**Comment by schickling** [comment]
This should be fixed in `1.3.10` 🎉
