### ISSUE TITLE
History and Headers aren't persisted

### ISSUE THREAD

**Issue by danwkennedy** [graphcool/graphql-playground#317]
#### This issue pertains to:

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground
- [ x ] GraphQL Playground Middleware

#### What OS and OS version are you experiencing the issue(s) on?
MacOS High Sierra

#### What version of graphql-playground(-electron/-middleware) are you experience the issue(s) on?
graphql-playground-middleware-koa: 1.3.6

#### What is the expected behavior?
The previous version we were on persisted the query history and headers when the page was refreshed.

#### What is the actual behavior?
The headers and history are cleared when the page refreshes. This causes some churn with Authorize headers needing to be set again in the case of the headers clearing. The history also becomes unusable since you can't see your history from previous development sessions.

**Comment by cjoudrey** [comment]
I think this is a bit of a deal breaking for people especially if they need to re-enter a `Authorization` header each time they boot the app.

I haven't taken a look, but we should be able to figure out what broke this feature using a `git bisect` once we know a previous version where this feature worked.

**Comment by vincenzo** [comment]
I believe this is the same as mine https://github.com/graphcool/graphql-playground/issues/312 -- If so, I can the "headers" bit there and we can close this one?

**Comment by vincenzo** [comment]
@timsuchanek @sorenbs

**Comment by timsuchanek** [comment]
Thanks for reporting @danwkennedy !
We will fix it in the coming days!

**Comment by vincenzo** [comment]
Hey, I had reported this days before :D

**Comment by vincenzo** [comment]
Can't wait for this to be fixed, to be honest.

**Comment by schickling** [comment]
This should be fixed in `1.3.10` 🎉

**Comment by cjoudrey** [comment]
Nice! I’ll bump the version in `brew cask` later if nobody does it before me.
