### ISSUE TITLE
Environment Variable Support

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/graphql-playground#336]
In order to fully support [GraphQL Config](https://github.com/graphcool/graphql-config) and the [Graphcool extension for GraphQL Config](https://github.com/graphcool/graphql-config-extension-graphcool/), environment variables need to be injected into the playground.
There are two sources of these env vars:
1. The `graphql` or `graphcool`
2. The middlewars (express, hapi, serverless etc)

# CLI ➝ Playground
Env vars could be injected over the `graphql-playground://` url, but the url limit is too low to just send all env vars.
Another approach would be to only send the necessary env vars. However, to find that out, all extensions would have to be traversed, still some env vars could be forgotton.
Because of that, the following flow will be implemented for now:
1. CLI puts env vars into a temporary file and sends the path to the playground
2. Playground reads the file and immediately deletes it.
```js
const os = require('os')
const opn = require('opn')
const envPath = path.join(os.tmpdir(), '/envvars/asdf.json')
fs.writeFileSync(envPath, JSON.stringify(envPath))


opn(`graphql-playground://?cwd=${process.cwd()}&envPath=${envPath}`)
```

Playground
```js
...on('OpenUrl', (url) => {
  const {cwd, envPath} = queryString.parse(url.slice(21))
  const envVarsString = fs.readFileSync(envPath, 'utf-8')
  const envVars = JSON.parse(envVarsString)
  fs.unlinkSync(envPath)
  // handle url as usual
})
```

# Middleware ➝ Playground
To get the env vars into the playground, the middleware passes them in with the stringified json of the options into the React component.
This works fine in dev mode, however, as soon as you want to host the playground in a production system, you can't afford to print all your env vars to the browser.
Because of that, the proposal is, to add a new option to the middleware components (Express, Hapi, ...) called `env`, which is an object that holds all env vars. This object is empty by default, so nobody is accidentally exposing secrets. It gives you fine-grain control over which env vars you want to send to the Playground web app.

There still might be env vars that both the GraphQL Config or the `graphcool.yml` might need.
As soon, as these are required, the Playground would then prompt the user to input the missing env vars.
They could, for example, be stored with localStorage or cookies. This way the endpoint doesn't expose unwanted information.

**Comment by timsuchanek** [comment]
This is by now fully implemented through the `graphql playground` and `prisma playground` commands.

**Comment by yassern** [comment]
hi, can this be used for reusable query variables between query and mutations?
