### ISSUE TITLE
Add AppX Support to Releases

### ISSUE THREAD

**Issue by deinok** [graphcool/graphql-playground#340]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Windows 10

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
Any

#### What is the expected behavior?
Have an AppX package

#### What is the actual behavior?
No AppX package

#### Description:
In order to have an AppX installation via Windows Store or as a package, build AppX packages via Desktop App Bridge or a better way if it exists.
The following code should generate an unsigned appx file:
`DesktopAppConverter.exe -Installer ./playground-setup-1.3.7.exe -InstallerArguments "/S" -Destination /output/ -PackageName "GraphQLPlayground" -Publisher "CN=GraphCool" -Version 1.1.3.0 -MakeAppx`

So it would be nice that the next releases also exists in this format ;)

**Comment by kbrandwijk** [comment]
Similar to (not to say: duplicate of) https://github.com/graphcool/graphql-playground/issues/225

**Comment by deinok** [comment]
Yeah, really similar, closing this
