### ISSUE TITLE
"graphcool playground" leads to exit code 1

### ISSUE THREAD

**Issue by marktani** [graphcool/graphql-playground#350]
#### This issue pertains to the following package(s):

- GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?

Mac OS X Sierra.

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

Version 1.3.9 (1.3.9)

#### What is the expected behavior?

running `graphcool playground` in a directory containing a `.graphqlconfig.yml`/`graphcool.yml` opens the GraphQL Playground electron app.

#### What is the actual behavior?

![image](https://user-images.githubusercontent.com/1780597/34070372-6401e2d6-e265-11e7-98f6-0edc785c47a1.png)

#### What steps may we take to reproduce the behavior?

```
npm i -g graphql-cli@beta
npm i -g graphcool@beta
graphql create my-dir
cd my-dir
graphcool deploy
graphcool playground
```

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by timsuchanek** [comment]
This is fixed in the latest version of prisma & the playground.
