### ISSUE TITLE
How to define Settings options?

### ISSUE THREAD

**Issue by orefalo** [graphcool/graphql-playground#359]
#### This issue pertains to the following package(s):

- [X] GraphQL Playground HTML
- [X] GraphQL Playground

What are the possible options in this file?!
How to point to a schema/server?

There used to be a simple to use UI, it's gone...

**Comment by kbrandwijk** [comment]
Intellisense would really help here. Pointing to a schema/server has nothing to do with the settings screen, as far as I know.

**Comment by orefalo** [comment]
Well, with the old pop up there was a field to enter the location of the server.
  Now that this is gone...

Never mind, I switched to Insomnia https://insomnia.rest/ - much better graphQL client anyways.
