### ISSUE TITLE
[1.3.8] Tracing is broken

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#360]
Occurs both in the electron & web version.

![image](https://user-images.githubusercontent.com/1567498/34104789-29bf2870-e3f2-11e7-9d20-3e9de462ad9b.png)

**Comment by schickling** [comment]
Seems to be a problem with https://github.com/apollographql/graphql-tools/pull/541

**Comment by kbrandwijk** [comment]
Are you sure? Playground isn't using 0.12...

**Comment by schickling** [comment]
That's true, especially when using the Electron app. We'll look into this again.

**Comment by kbrandwijk** [comment]
Is this related to `tracing.hideTracingResponse`? Maybe it deletes it from the response before it is rendered in the tracing view? Haven't tested it though, just my 2c.

**Comment by blakek** [comment]
This works properly in the web version but I can't get the newest version of the Electron app to work at all.
