### ISSUE TITLE
`gc playground` & `graphql playground` not working when no `.graphqlconfig` is there

### ISSUE THREAD

**Issue by nikolasburk** [graphcool/graphql-playground#363]
At least `graphcool playground` should work when no `.graphqlconfig` is present (which also brings up a question about whether both commands should behave exactly the same).

**Comment by timsuchanek** [comment]
This is an issue in the Graphcool cli, closing in favor of https://github.com/graphcool/framework/issues/1441

**Comment by timsuchanek** [comment]
The CLI part is done, there is a change in the Playground needed

**Comment by timsuchanek** [comment]
This is fixed in the latest version.
