### ISSUE TITLE
playground session based auth, not sending cookie in the request.

### ISSUE THREAD

**Issue by gwenvaelmahe** [graphcool/graphql-playground#364]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Chrome/Opera

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.3.6

#### What is the expected behavior?
Send cookie on the request.

#### What is the actual behavior?
Not sending the cookie in the request, unlike graphiQL.

#### What steps may we take to reproduce the behavior?
We're using passport-local as a middleware.
We use the mutation login and if it works we get back a cookie.
If I want to check who is the current user, I send my query and the cookie (passport) should be included in the request where the resolver should return either the current user or null in case the user has logout or if the cookie wasn't sent.

what graphiQL is sending:
<img width="842" alt="screen shot 2017-12-21 at 16 24 40" src="https://user-images.githubusercontent.com/4230611/34264692-9d817fa8-e66b-11e7-9d21-0a48bb41be30.png">
What playground is sending:
<img width="848" alt="screen shot 2017-12-21 at 16 24 18" src="https://user-images.githubusercontent.com/4230611/34264693-9d9746b2-e66b-11e7-872e-163bad99f9bd.png">

**Comment by vincenzo** [comment]
I confirm this one is still a problem with Playground `1.3.10` (included in Yoga `0.4.4`)

**Comment by vincenzo** [comment]
/cc @timsuchanek @kbrandwijk 

I'd love if this issue could get priority attention, as it's affecting us in our development (we use Yoga). If there's anyone else that should be explicitly tagged, please do.

**Comment by Huvik** [comment]
@vincenzo You can always chip in and help with it :)

**Comment by vincenzo** [comment]
@Huvik I'd love to, but I am new to all this and don't really know where to start to fix this one, sorry :) Maybe someone in my team could help. I'll ask.

**Comment by vincenzo** [comment]
@Huvik @timsuchanek Any of you could give me a steer in the right direction, here?
