### ISSUE TITLE
HTTP headers should not be reformatted to lower-case

### ISSUE THREAD

**Issue by nickdecooman** [graphcool/graphql-playground#370]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Mac OSX 10.12.6

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

1.3.12.12

#### What is the expected behavior?
When entering a HTTP header with one or more upper-case letters, the exact same value is expected to be passed in the HTTP request.

#### What is the actual behavior?
Currently, the HTTP headers seem to be reformatted to a lower-case version before being sent.

#### What steps may we take to reproduce the behavior?
Enter the following JSON in HTTP Headers section: 
`{
  "Authorization": "foobar"
}`

The actual header that will be sent is `authorization`

**Comment by kbrandwijk** [comment]
HTTP Headers are case-insensitive by spec. RFC 7230 states: 
> Each header field consists of a case-insensitive field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace.

**Comment by timsuchanek** [comment]
As @kbrandwijk stated, HTTP Headers are case insensitive.
