### ISSUE TITLE
Variable editor is broken

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#372]
Seems like the variable editor is broken in one of the recent releases.

Error message:

![image](https://user-images.githubusercontent.com/1567498/34439349-8b6ee542-ecad-11e7-9441-06d966e22c16.png)

Example:

```graphql
input UserCreateInput {
  role: Role!
  email: String
  password: String
  posts: PostCreateManyWithoutAuthorInput
}

mutation ($_data: UserCreateInput!) {
  createUser(data: $_data) {
    id
  }
}
```

```json
{
  "_data": {
    "role": "CUSTOMER",
    "email": "testa10",
    "password": "testest"
  }
}
```

**Comment by sorenbs** [comment]
It seems that Playground always treats variables as optional even when they are used for a variable that is required.

Here's the error message so others can find this issue by searching:

```
Uncaught Error: Can only create NonNull of a Nullable GraphQLType but got
```
