### ISSUE TITLE
Operation selection doesn't work

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#373]
This is a regression bug:

- [ ] Operation needs to be selectable via play button
- [ ] Operation should be automatically selected when pressing `CMD + Enter` when cursor is inside an operation

![image](https://user-images.githubusercontent.com/1567498/34439901-a203771a-ecb1-11e7-966a-4e6f590bd798.png)

**Comment by marktani** [comment]
This should be fixed, please open a new issue if you encounter it again.
