### ISSUE TITLE
lambda middleware returns promise as body, not string

### ISSUE THREAD

**Issue by josephktcheung** [graphcool/graphql-playground#374]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [X] GraphQL Playground Hapi Middleware
- [X] GraphQL Playground Koa Middleware
- [X] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
MacOS High Sierra Version 10.13.2

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
graphql-playground-lambda@1.3.6

#### What is the expected behavior?
It should work

#### What is the actual behavior?
`body` returned by [`renderPlaygroundPage`](https://github.com/graphcool/graphql-playground/blob/master/packages/graphql-playground-middleware-lambda/src/index.ts#L17) is a promise, not string.

I haven't tested hapi and koa middleware, but I believe they may suffer the same problem because `renderPlaygroundPage` becomes async function in new version of `graphql-playground-middleware-html` but lambda, hapi and koa middleware haven't been updated accordingly.

#### What steps may we take to reproduce the behavior?
You can clone my fork on [`serverless-graphql`'s `feature/fix_production` branch](https://github.com/josephktcheung/serverless-graphql/tree/feature/fix_production), then
```
npm install -g serverless
npm install -g yarn
yarn install
cd app-backend/rest-api
yarn start
```
open playground page
```
http://localhost:4000/playground
```

_Please provide a gif or image of the issue for a quicker response/fix._
![screen shot 2018-01-01 at 6 11 49 pm](https://user-images.githubusercontent.com/4270232/34466952-4945c874-ef1f-11e7-9a3d-5a92b3b17d77.png)

**Comment by timsuchanek** [comment]
This is fixed in the latest version.
