### ISSUE TITLE
Inclusion into graphql and graphcool CLI

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/graphql-playground#375]
In order to provide a seamless developer experience, when using the `graphql` and `graphcool` CLI, the following points have to be considered.

## Source of truth
The source of truth, where services and endpoints should be injected in the GraphQL Playground, is the `graphcool.yml`. As described here, we're moving away from and CLI args dependencies, all relevant information is pulled out of the `graphcool.yml` https://github.com/graphcool/framework/issues/1461

## Multiple stages
Multi-stage support in the GraphQL Playground will for now look like this:
One Playground App window will only represent one stage, as stages are now being injected by environment variables into the `graphcool.yml`.

## Dotenv support
We might consider putting in `dotenv` support for these env var surface points.
This could for example be a drop-down in the "Open Workspace" dialog of the Playground App.

**Comment by wtgtybhertgeghgtwtg** [comment]
I'd ask that it actually go the other way.  Users of `graphql-playground` are not necessarily users of `graphcool`.

**Comment by timsuchanek** [comment]
This is implemented in the `graphql-config-extension-graphcool`
