### ISSUE TITLE
Visual indicator when schema was reloaded

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#379]
Visual feedback is one of the most important components to a great UX. When developing a GraphQL server, you're changing your schema quite often. This workflow is being steadily improved by allowing `CMD + R` to reload the schema (#180) and even automatic schema reloads based on filewatching via graphqlconfig (#331).

I suggest to introduce a nice visual animation (some sort of pulse & rotation - maybe even colored) when the schema has been reloaded.

![image](https://user-images.githubusercontent.com/1567498/34521367-b26a8faa-f08d-11e7-9fef-b35b750e8632.png)

@xavcz maybe you have some idea how we could design/implement this? 👨‍🎨

**Comment by Huvik** [comment]
I was thinking maybe do something like Firefox quantum is doing with reload and maybe just small popup in bottom to just alert that schema was reloaded. Something like `hyper` is doing with new version.
![Firefox](https://i.imgur.com/xUX136M.gif)

**Comment by xavcz** [comment]
> Visual feedback is one of the most important components to a great UX.

:100: yay, I'm going to give it a try!

**Comment by xavcz** [comment]
Here is what I came up with so far:

![gif recording of the frame prototype](https://cl.ly/1i1M0g0E261V/graphql-playground.gif)

Live prototype here: https://framer.cloud/iGRSF

What do you think?

**Comment by kbrandwijk** [comment]
@xavcz I love the visuals, but as soon as the reload is done there's no trace that it ever happened. 

I think a more permanent indication of schema reload (last updated ...) might be more suitable.

**Comment by schickling** [comment]
Hi @xavcz! Thanks a lot for your suggestion! I really like the general idea but think replacing the icon with the GraphQL logo is a bit "overkill". I'd rather expect the reload button to turn into some kind of rotating reload animation (like the one on the [bottom right](https://loading.io/css/)). What do you think?

Regarding @kbrandwijk remark. How about displaying a little notification dot (similar how the Twitter feed does it) next to the reload icon which is there until you change/run a query.

**Comment by xavcz** [comment]
Aaaah, "simplicity is the ultimate sophistication". Thanks for the feedbacks and making me get down on the ground!

👌, stay tuned

**Comment by xavcz** [comment]
> Better late than never

Simple PR opened with some questions/comments!

**Comment by timsuchanek** [comment]
Awesome! Will look into it :)
