### ISSUE TITLE
Subscription display broken in latest version

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-playground#389]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [X] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

![image](https://user-images.githubusercontent.com/852069/34554386-e1ca4c46-f12c-11e7-9a4e-45556b275fd7.png)

**Comment by timsuchanek** [comment]
This is fixed in the latest version
