### ISSUE TITLE
App crashes when toggling between endpoints or closing tabs

### ISSUE THREAD

**Issue by havgry** [graphcool/graphql-playground#393]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?

MacOS High Sierra 10.13.2

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

1.3.19 (1.3.15 seems to be working fine)

#### What is the expected behavior?

No errors.

#### What is the actual behavior?

App goes blank and has to be restarted and the following error is thrown: `Cannot read property 'getWrappedInstance' of null`

<img width="1200" alt="graphcool playground error" src="https://user-images.githubusercontent.com/3898396/34560484-2bc7ae10-f146-11e7-9acc-7d74a777c6e1.png">

#### What steps may we take to reproduce the behavior?

Close a tab or toggle between endpoints.

**Comment by Huvik** [comment]
Are you sure its 1.3.19?

**Comment by havgry** [comment]
@Huvik 100%

To be exact the issue seems to have been introduced in 1.3.17.

**Comment by Huvik** [comment]
Yea, but should be fixed in 1.3.19 🤔

**Comment by Huvik** [comment]
Okey i will look into it again today, sorry for troubles

**Comment by havgry** [comment]
No worries 👍

**Comment by Huvik** [comment]
Yea, its because inside Electron playground is still version 1.3.17

**Comment by Huvik** [comment]
Its fixed in #397
