### ISSUE TITLE
Playground not loading on Serverless with Lambda Middleware version 1.3.6

### ISSUE THREAD

**Issue by sebnyberg** [graphcool/graphql-playground#394]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [x] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

Ubuntu 16.04 and Windows 10

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

graphql-playground-middleware-lambda 1.3.6

#### What is the expected behavior?

The playground should load as usual.

#### What is the actual behavior?

On Servless Offline you get

```json
{"domain":{"domain":null,"_events":{},"_eventsCount":1,"members":[]}}
```

or on AWS you get

```json
{"message": "Internal server error"}
```

#### What steps may we take to reproduce the behavior?

1. Remove yarn.lock in either `graphql-playground-middleware-lambda/examples/basic` or `serverless-graphql/app-backend/rest-api` 
2. Run `yarn install` or `npm install`
3. Start with `serverless deploy`

**Comment by sebnyberg** [comment]
Setting the version to 1.3.1 solves the issue

**Comment by kbrandwijk** [comment]
And what about the latest version, because it's already on 1.3.19?

**Comment by sebnyberg** [comment]
The latest version in the NPM registry seems to be 1.3.6

**Comment by divyenduz** [comment]
Hello, 

I think I am facing an issue related to this, I am working on an example with following dependencies:- 
```
"graphcool-binding": "1.3.1",
"graphql-yoga": "1.1.1",
```

The `GraphQLServer` from `graphql-yoga` gets a working middleware path - `http://cdn.jsdelivr.net/npm/graphql-playground-react@1.3.20/build/static/js/middleware.js`

But `GraphQLServerLambda` from `graphql-yoga` gets me a 404 middleware path - `http://cdn.jsdelivr.net/npm/graphql-playground-react@1.3.7/build/static/js/middleware.js`

I tried to setup this on local to attempt a fix by linking `graphql-yoga`, `graphql-playground` to in order but I think I am missing something there. 

Also, I wanted to know why do we have different packages in `graphql-playground`, do they need to be linked separately for development? What are the upsides of doing it in this way over say having one release for `graphql-playground` itself and whenever a sub-package changes, we can bump up the version of `graphql-playground`. Just curious about the though process behind current structure. 

Thanks.

**Comment by schickling** [comment]
This should be fixed with `graphql-playground-middleware-lambda@1.3.9` ✅
