### ISSUE TITLE
Opening local folder with env variables doesn't work

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-playground#395]
#### This issue pertains to the following package(s):

- [X] GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?
Windows 10

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.3.19

#### What is the expected behavior?
Opening a folder with a .graphcool.yml file with env placeholders and a .env file should work.

#### What is the actual behavior?
Error: 
![image](https://user-images.githubusercontent.com/852069/34561368-ee5d1bb0-f149-11e7-89c8-710ab96b1e57.png)

#### What steps may we take to reproduce the behavior?
Download the `graphcool-server-example` repo, and try to open it.

**Comment by marktani** [comment]
Also confirmed on Mac OS X: #456.

**Comment by schickling** [comment]
Still seems to be the case:

![image](https://user-images.githubusercontent.com/1567498/38189237-7baa32dc-365f-11e8-834c-9ec51763b8ec.png)

**Comment by timsuchanek** [comment]
Thanks for the help everyone! It's fixed in 1.5.2.
