### ISSUE TITLE
Auto upgrader doesn't reopen project

### ISSUE THREAD

**Issue by marktani** [graphcool/graphql-playground#437]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?

Mac OS X Sierra

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

`1.3.20`

#### What is the expected behavior?

When running auto-upgrade and a project is open, it should upgrade the Playground and then reopen the project.

#### What is the actual behavior?

When running auto-upgrade and a project is open, it doesn't re-open the project after auto-upgrading.

#### What steps may we take to reproduce the behavior?

Download version `1.3.20`, open a project, wait for auto-upgrader to kick in.

**Comment by Huvik** [comment]
Same as #382
