### ISSUE TITLE
Opening a folder that contains a valid config doesn't work

### ISSUE THREAD

**Issue by marktani** [graphcool/graphql-playground#456]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?

Mac OS X Sierra

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

`Version 1.3.21 (1.3.21.257)`

#### What is the expected behavior?

Opening a folder with a valid `.graphqlconfig.yml`/`graphcool.yml` file works.

#### What is the actual behavior?

It doesn't work.

![image](https://user-images.githubusercontent.com/1780597/34580630-f0c9afc8-f18d-11e7-8c61-e2508dbff749.png)

#### What steps may we take to reproduce the behavior?

Use the blue "Open" button in the welcome screen to open a folder with a valid `.graphqlconfig.yml`/`graphcool.yml` file:

![image](https://user-images.githubusercontent.com/1780597/34580641-fa71783a-f18d-11e7-85c3-bae67b9f1c94.png)

**Note:** it's essentially the same error as this one: https://github.com/graphcool/graphql-config-extension-graphcool/issues/6

The difference is that here, I am opening the folder from the UI, and in the other issue I am opening the folder using `graphql playground`.

**Comment by kbrandwijk** [comment]
Related to #395?

**Comment by marktani** [comment]
Yep duplicate! Thanks 🙏
