### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#459]
Some error cases are quite common and should be handled more gracefully:

- "Failed to fetch" should be more helpful
- database is not online: currently the entry is not visible, maybe it should be there but with a grey circle indicating it's offline?

![image](https://user-images.githubusercontent.com/1567498/34521334-89e37150-f08d-11e7-9086-2f272ce114be.png)

**Comment by timsuchanek** [comment]
Implemented in latest version.
