### ISSUE TITLE
Playground not loading because assets are at 404

### ISSUE THREAD

**Issue by divyenduz** [graphcool/graphql-playground#465]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [x] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
macOS High Sierra - Version - 10.13.2 (17C88)

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
graphql-playground-middleware-lambda - 1.3.7

#### What is the expected behavior?
The playground when loaded from lambda with `graphql-yoga` as the primary dependency should work correctly, as `graphql-yoga` is abstracting underlying dependencies like `graphql-playground-middleware-lambda`, it should be opaque to the developer and load the correct playground assets. 

#### What is the actual behavior?
An attempted serverless local deploy with `npm start` in [this repository](https://github.com/divyenduz/graphql-serverless-deploy-example) resolved to 404 URL for playground assets. 

#### What steps may we take to reproduce the behavior?
Clone - https://github.com/divyenduz/graphql-serverless-deploy-example
Run 
```
npm install
npm start
```
Open http://localhost:3000 and check network tab. 

![pasted_image_at_2018_01_06_11_21_am](https://user-images.githubusercontent.com/746482/34638922-bc7ef164-f2fb-11e7-8e3e-3add44a33528.png)

**Comment by schickling** [comment]
I've just released a new version. Can you verify this is still a problem?

**Comment by schickling** [comment]
This should be fixed with `graphql-playground-middleware-lambda@1.3.9` ✅

**Comment by divyenduz** [comment]
I can confirm that this is resolved. Thanks for the super quick turnaround.

**Comment by chrischiancone** [comment]
I am having the same issue, reproduced all the steps above. Not receiving any errors on the console, but {"statusCode":404,"error":"Not Found","message":"Not Found"} on console log.
