### ISSUE TITLE
Type Link in Autocomplete Dropdown broken.

### ISSUE THREAD

**Issue by do4gr** [graphcool/graphql-playground#495]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

OsX Safari
OsX Chrome

#### What steps may we take to reproduce the behavior?
Click on the type definition in the autocomplete dropdown menus. Then you get a blank page with only the dropdown remaining. Refreshing the tab clears the issue, but it can be triggered again by clicking the type again.

I would expect that clicking the type opens a new tab or forwards to the full type definition or maybe expands the schema sidenav. 

<img width="1263" alt="bildschirmfoto 2018-01-15 um 10 49 58" src="https://user-images.githubusercontent.com/16278407/34936632-71b30556-f9e2-11e7-86e4-1e8246616921.png">

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by Weakky** [comment]
I started digging up this issue.

```js
  private onClickHintInformation = event => {
    if (event.target.className === 'typeName') {
      const typeName = event.target.innerHTML
      const schema = this.state.schema
      if (schema) {
        const type = schema.getType(typeName)

        if (type) {
          this.setState({ docExplorerOpen: true } as State, () => {
            this.docExplorerComponent.showDoc(type)
          })
        }
      }
    }
  }
```

This only issue I'm facing is with X-to-many types. Whenever types are within arrays, `schema.getType(typeName)` returns `typeName`, which is a `String`.
As it doesn't find the type, I can't either use `getDeeperType()` to find its root type.

Are there any clean way to find a type such as `[Person!]` in the schema, from the type's name only ?

**Comment by timsuchanek** [comment]
@Weakky awesome that you're looking into this!

The code `this.docExplorerComponent.showDoc()` is still an artifact from the old graphiql code.
The new `GraphDocs` component doesn't have this feature yet.
So you can right now either just out comment this, as this code is not used anyways or implement the functionality to click on hint items and highlight them in the `GraphDocs`.

To do that, you would add the `showDoc(type)` as an action in redux and the `GraphDocs` component and call it from the `onClickHintInformation` function you just posted.

You can join our Graphcool slack and ping me `@tim2` if you have any questions about the implementation.
