### ISSUE TITLE
TypeError: Cannot read property 'attach' of undefined

### ISSUE THREAD

**Issue by jvbianchi** [graphcool/graphql-playground#530]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
MacOS 10.12.6

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
Electron 1.4.2

#### What is the expected behavior?
Don't have this error

#### What is the actual behavior?
The electron app is unusable.
Open the electron app and saw this error on Developer Tools

#### What steps may we take to reproduce the behavior?
Use this boilerplate: https://github.com/graphql-boilerplates/typescript-graphql-server
and run `npm run dev`

_Please provide a gif or image of the issue for a quicker response/fix._
![screen shot 2018-01-23 at 10 02 56](https://user-images.githubusercontent.com/13983663/35274797-9e43a6fa-0024-11e8-94d8-b6e014133982.png)

**Comment by jvbianchi** [comment]
Maybe related to https://github.com/graphcool/graphql-playground/issues/491

**Comment by timsuchanek** [comment]
Thanks for reporting, @jvbianchi ! Can you try the latest `graphql-playground-middleware-express` package? That has hopefully fixed this!

**Comment by jvbianchi** [comment]
The latest version 1.4.3 solved this issue
