### ISSUE TITLE
Downloading the app is slow for .deb package 

### ISSUE THREAD

**Issue by Altiano** [graphcool/graphql-playground#550]
I live in Indonesia. My internet connection is fine (~200 KB). But, the download speed for .deb package just about 15 - 40 KB

**Comment by timsuchanek** [comment]
Thanks for reporting @Altiano! We're using the Github hosting for the release, which we won't change for now. I guess there are other factors that we can't influence that make the download slow.

As we can't really do anything about it, I'm closing the issue for now.
If other people experience similar problems, please report.
Thanks!
