### ISSUE TITLE
High CPU usage in Electron app

### ISSUE THREAD

**Issue by tamlyn** [graphcool/graphql-playground#569]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
OSX 10.11 on 2015 Macbook Pro

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
Version 1.4.3 (1.4.3.2587

#### What is the expected behavior?
Should not consume much CPU when idle.

#### What is the actual behavior?
Having the app open consumes >100% cpu, even when idle and in the background.

#### What steps may we take to reproduce the behavior?
Open the app.

![screenshot 2018-02-13 11 44 37](https://user-images.githubusercontent.com/115310/36148457-145bd962-10b4-11e8-966c-45e7daca23eb.png)
 
The left part of the CPU histogram is with the app closed and general web browsing. The right part is with the app open but not being used. CPU usage is high on first opening the app then increases further after opening a workspace (the Github API in this case).

**Comment by peterschussheim** [comment]
I have the same experience as @tamlyn reports, with the electron application and the web app.

### electron
<img width="374" alt="graphql playground001" src="https://user-images.githubusercontent.com/3654683/36173453-14798778-10d7-11e8-86fb-754c953d5134.png">

### web
<img width="1157" alt="google chrome012" src="https://user-images.githubusercontent.com/3654683/36173569-78df89a6-10d7-11e8-9be5-5628fa990c80.png">

**Comment by schickling** [comment]
@timsuchanek is currently looking into this. See #320 (closing as duplicate).
