### ISSUE TITLE
TypeScript error when `yarn start`-ing the electron app? 

### ISSUE THREAD

**Issue by rmosolgo** [graphcool/graphql-playground#588]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

OSX Sierra

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

I cloned 772a04cfc684c2e38c376a9ef3abe311090c96d4

#### What is the expected behavior?

I can develop the electron app according to the Readme: 

https://github.com/graphcool/graphql-playground/blob/772a04cfc684c2e38c376a9ef3abe311090c96d4/packages/graphql-playground-electron/README.md#L6-L9

#### What is the actual behavior?

It fails with a typescript compile error: 

```
~/code/graphql-playground/packages/graphql-playground-react $ cd ../graphql-playground-electron
~/code/graphql-playground/packages/graphql-playground-electron $ yarn install
yarn install v1.5.1
warning package.json: No license field
warning graphql-playground-electron@1.4.4: No license field
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.80s.
~/code/graphql-playground/packages/graphql-playground-electron $ yarn start
yarn run v1.5.1
warning package.json: No license field
$ yarn build:ts && concurrently "yarn start:react" "wait-on http://localhost:4040/ && yarn start:electron"
warning package.json: No license field
$ rimraf lib && tsc
src/renderer/components/App.tsx(550,17): error TS2339: Property 'platformToken' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<MiddlewareApp> & Readonly<{ children?: ReactNode; ...'.
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: sh
Arguments: -c rimraf lib && tsc
Directory: /Users/rmosolgo/code/graphql-playground/packages/graphql-playground-electron
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/rmosolgo/code/graphql-playground/packages/graphql-playground-electron/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c yarn build:ts && concurrently \"yarn start:react\" \"wait-on http://localhost:4040/ && yarn start:electron\"
Directory: /Users/rmosolgo/code/graphql-playground/packages/graphql-playground-electron
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/rmosolgo/code/graphql-playground/packages/graphql-playground-electron/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### What steps may we take to reproduce the behavior?

- Clone the project 
- Enter the `packages/graphql-playground-electron` 
- `yarn install && yarn start`

**Comment by schickling** [comment]
Thanks a lot for reporting this @rmosolgo. We'll look into it!

**Comment by timsuchanek** [comment]
Thanks for reporting @rmosolgo and sorry for getting back so late to you!
This should be fixed by now. Can you confirm? Thanks!

**Comment by rmosolgo** [comment]
Yes, I pulled master, `yarn install`ed and `yarn start`ed and it booted up. Thanks for the update!
