### ISSUE TITLE
Publish `graphql-playground-react-build` as bundled, zero-dependency version

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#594]
To make the life easier for other non-JS based GraphQL server implementations (Java, Ruby, Scala ...) to embed the Playground we should:

1) Publish a new package `graphql-playground-react-build` as bundled, zero-dependency version
2) Provide some documentation on how to embed the GraphQL Playground in a non-JS context

**Comment by RStankov** [comment]
This would be very helpful in building the `graphql-playground-rails` gem.

**Comment by timsuchanek** [comment]
Good point! Just added a section to the README about this https://github.com/graphcool/graphql-playground#as-html-page
