### ISSUE TITLE
Always executes first operation, no multi selection popup for Play button

### ISSUE THREAD

**Issue by marktani** [graphcool/graphql-playground#609]
#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

The in-browser Playground for Prisma services deployed to cluster version `1.4.2` at the moment.

#### What is the expected behavior?

* Ctrl+Enter executes the command that is currently "selected" with the cursor 
* clicking Play button opens a small multi-selection popup when multiple operations are defined

#### What is the actual behavior?

* Ctrl+Enter always executes the first operation
* clicking Play button always executes first operation

#### What steps may we take to reproduce the behavior?

Go to https://eu1.prisma.sh/public-springpaladin-62/set-json-list/dev.
Define two operations:

```
npm install -g prisma@1.4.2
prisma init test
cd test
prisma deploy # open new endpoint in browser
```

Now defined two operations - for example one query and one mutation - in the same tab. Try to execute the second.

**Comment by sirctseb** [comment]
hi @timsuchanek, we're seeing this behavior in our use of graphql-playground as an express middleware. did this issue get moved somewhere that we can follow or assist somehow?
