### ISSUE TITLE
Renaming tabs doesn't work on Linux

### ISSUE THREAD

**Issue by marktani** [graphcool/graphql-playground#616]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App

haven't tried the rest

#### What OS and OS version are you experiencing the issue(s) on?

Linux

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

I downloaded the amd64 asset from here: https://github.com/graphcool/graphql-playground/releases/tag/v1.5.0-rc.5/.

#### What is the expected behavior?

Double clicking the tab name, then typing something works

#### What is the actual behavior?

Double clicking the tab name works, the name becomes empty and the cursor becomes invisible. Typing then results in nothing.

**Comment by timsuchanek** [comment]
Fixed in latest version.
