### ISSUE TITLE
Connection errors not displayed in response panel since 1.5

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#626]
When the underlying server is unavailable and a request is sent, the response panel should display a helpful error message. Instead it's currently just empty.

![image](https://user-images.githubusercontent.com/1567498/38195086-f6eea63c-367b-11e8-94b0-fd018444c4ef.png)

Additionally the playground should fallback into the "ping polling" state until the server is reachable again:

![image](https://user-images.githubusercontent.com/1567498/38195161-5756d2ce-367c-11e8-91dd-42f714a0c3fd.png)

**Comment by timsuchanek** [comment]
Fixed in 1.5.1.
