### ISSUE TITLE
All get lost on updates

### ISSUE THREAD

**Issue by kikoseijo** [graphcool/graphql-playground#629]
In every update all I had saved its lost.
Is there I way I can recover it all? or don't overwrite by updates, 

its a nightmare!!!!!

**Comment by timsuchanek** [comment]
Thanks @kikoseijo ! We did put a warning into the release notes about exactly this. Did this happen to you through auto update? You can install an older release (<1.5) and all the data should still be there!

**Comment by kikoseijo** [comment]
Hey @timsuchanek,

Yes its the auto update app for Mac, been happening on the last 3-4 updates, yes.

Lets hope it will settle eventually... thanks for support,
