### ISSUE TITLE
"Server cannot be reached" does not take new headers into account

### ISSUE THREAD

**Issue by marktani** [graphcool/graphql-playground#632]
#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

The in-browser Playground deployed to Prisma endpoints.

#### What is the expected behavior?

Consider this ideal scenario:

* Open a Prisma endpoint protected by a secret
* Introspection query is run
* Introspection query is "blocked" by server, due to secret
* "Server cannot be reached" state is activated
* the correct Authorization header is added
* Playground exists "Server cannot be reached" state
* Introspection query is successfully executed

Normal usage of Playground is possible from now on

#### What is the actual behavior?

Consider the actual scenario:

* Open a Prisma endpoint protected by a secret
* Introspection query is run
* Introspection query is "blocked" by server, due to secret
* "Server cannot be reached" state is activated
* the correct Authorization header is added
* Playground is stuck in "Server cannot be reached" state

Reload required to move on.

#### What steps may we take to reproduce the behavior?

See above.

**Comment by timsuchanek** [comment]
This should be fixed in the latest Playground. Can you confirm @marktani ?

**Comment by marktani** [comment]
I can, thanks for fixing it 🙂
