### ISSUE TITLE
Reloading the schema file doesn't affect autocompletion and syntax checking

### ISSUE THREAD

**Issue by marktani** [graphcool/graphql-playground#637]
#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

The one that is shipped to Prisma services as of today.

#### What is the expected behavior?

* have a valid query in the query view
* deploy a change to your prisma service that makes that query invalid
* click the reload schema button
* the autocompletion is still like before, as is the syntax checking
* reloading the browser page applies the right schema 

#### What is the actual behavior?

Reloading the browser page shouldn't be necessary to reload the schema used for autocompletion and syntax checking.

#### What steps may we take to reproduce the behavior?

See above.

**Comment by timsuchanek** [comment]
Thanks for reporting @marktani ! Can you check if that is fixed in the latest Playground version?

**Comment by marktani** [comment]
I can still reproduce this using `1.5.4` electron app.

**Comment by timsuchanek** [comment]
A fix has been released :)
