### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toJS' of undefined at HistoryPopup.render

### ISSUE THREAD

**Issue by jeromemacias** [graphcool/graphql-playground#643]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
MacOS 10.13.4

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.5.4

#### What is the expected behavior?
Click on tab "History" works when no history

#### What is the actual behavior?
Uncaught TypeError: Cannot read property 'toJS' of undefined
    at HistoryPopup.render (app.87c01a5….js:171911)

#### What steps may we take to reproduce the behavior?
Click on one of sample projects on start, then click on "History tab"

_Please provide a gif or image of the issue for a quicker response/fix._
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/582446/38768788-25ba47c4-3ff9-11e8-95e9-3ac00f487eed.png">

**Comment by tjpeden** [comment]
I too am having this issue. Is there any workaround? It's completely unusable now.

**Comment by jetpackjarrett** [comment]
@tjpeden clearing cache/cookies solved it for me.

**Comment by hsiaosiyuan0** [comment]
rebuilding from latest codebase resolves this issue:

```bash
$ git clone git@github.com:graphcool/graphql-playground.git
$ cd graphql-playground/packages/graphql-playground-electron
$ yarn
$ yarn run release:mac # release:win release:linux
```
