### ISSUE TITLE
Broken Playground since 1.5.5

### ISSUE THREAD

**Issue by Weakky** [graphcool/graphql-playground#654]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?

Mac OS 10.13.3

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

1.5.5

#### What is the behavior?

The editors are completely broken. Syntax colorization is gone, so is the autocompletion. I can't even click the "play" button to query my api.

#### What steps may we take to reproduce the behavior?

Not sure yet, I've just updated the playground and got it broken this way.

<img width="1196" alt="capture d ecran 2018-04-25 a 09 39 09" src="https://user-images.githubusercontent.com/25233379/39232125-8cf09bac-486c-11e8-8b87-9d38367760e8.png">

**Comment by timsuchanek** [comment]
Thanks for reporting @Weakky. We just released a pre-release that aims on this problem.
https://github.com/graphcool/graphql-playground/releases/tag/v1.5.6
Can you manually download the .dmg from the release page and try it out?
Thanks!

**Comment by timsuchanek** [comment]
Just released 1.5.6. Please let me know if this is still in issue.
