### ISSUE TITLE
Playground Bug?

### ISSUE THREAD

**Issue by idkjs** [graphcool/graphql-playground#672]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?

macOS Sierra
Starting playground always throws this error
https://prisma.slack.com/archives/CA491RJH0/p1525868753000241

You can click past it so not horrible. FYI.

**Comment by ddekkers** [comment]
Can you provide more information about this bug as not everybody is registered on the prisma slack channel?

**Comment by idkjs** [comment]
Run prisma playground in any graphql-cli boilerplate. You will get that window when electron version of playground opens up. Maybe for browser version as well. Seem harmless in that you can click past it and go about your way.

**Comment by marktani** [comment]
Thanks @idkjs this looks to be covered in #670 🙂
